services:
  # ===== Metrics =====
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devsecops-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - devsecops-net

  # ===== Logs =====
  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - devsecops-net

  promtail:
    image: grafana/promtail:2.9.6
    container_name: promtail
    volumes:
      # promtail config
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      # accès aux logs docker
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - devsecops-net

  # ===== Dashboard + Alerting =====
  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Active provisioning + alerting
      - GF_UNIFIED_ALERTING_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    depends_on:
      - loki
      - prometheus
    networks:
      - devsecops-net

networks:
  devsecops-net:
    external: true
    name: devsecops-lab_default
